# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(related_name='friends', to='main.User'),
        ),
    ]
