# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180208_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user_id',
            new_name='user',
        ),
    ]
